# -*- coding: utf-8 -*-
"""CovidDataCleaing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eXU1PsIBsP8xBLtYwmuyuWnFpBrgW4vV
"""

import pandas as pd

# Read in the data
df = pd.read_csv('owid-covid-data.csv')

# move population column and extract death data
cols = df.columns.tolist()
new_cols = cols[0:4] + ['population'] + cols[4:26]
deads = df[new_cols]
deads.to_excel('CovidDeaths.xlsx')

# extract the vaccination data
new_cols_2 = cols[0:4] + cols[26:]
vac = df[new_cols_2]
vac.to_excel('CovidVaccinations.xlsx')